FROM agrdocker/agr_javascript_env:latest as ui_env

WORKDIR /workdir/agr_ui

ADD . .
RUN npm install

ARG NODE_ENV=development
ENV NODE_ENV ${NODE_ENV}

RUN npm run build
RUN npm test


FROM nginx

WORKDIR /workdir/agr_ui
COPY --from=ui_env /workdir/agr_ui .

WORKDIR /etc/nginx/conf.d

ADD nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 2992
