FROM agrdocker/agr_javascript_env:latest

WORKDIR /workdir/agr_ui

ADD . .
RUN npm install

ARG NODE_ENV=development
ENV NODE_ENV ${NODE_ENV}

ARG LIVE_UI=true
ENV LIVE_UI ${LIVE_UI}

RUN npm run build
RUN npm test
