FROM agrdocker/agr_base_linux_env:latest

WORKDIR /workdir/agr_ui

ADD . .
RUN npm install

ARG NODE_ENV=development
ENV NODE_ENV ${NODE_ENV}

ARG LIVE_UI=true
ENV LIVE_UI ${LIVE_UI}

ARG RELEASE=0.0.0
ENV RELEASE ${RELEASE}

RUN npm run build
RUN npm test
