
export const TRACK_TYPE = {
  ISOFORM_EMBEDDED_VARIANT:'ISOFORM_EMBEDDED_VARIANT',
  ISOFORM_AND_VARIANT:'ISOFORM_AND_VARIANT',
  ISOFORM:'ISOFORM',
  VARIANT:'VARIANT',
  VARIANT_GLOBAL:'VARIANT_GLOBAL',
};
