export const HELP_AUTOMATED_GENE_DESCRIPTION =
  'This gene description is generated by an algorithm developed by the Alliance that uses highly structured gene data such as associations to various ontology terms (e.g., Gene Ontology terms) and the Alliance strict orthology set. The original set of ontology terms that a gene is annotated to may have been trimmed to an ancestor term in the ontology, in order to balance readability with the amount of information in the description. The complete set of annotations to this gene may be found in the relevant data tables below.';

export const HELP_CROSS_REFERENCES_GCRP =
  'GCRP stands for the UniProtKB Gene Centric Reference Proteome and represents the single UniProtKB GCRP ID for any given gene. This ID can be used, for example, when linking out to AlphaFold for protein folding predictions or when needing to reference a gene using a single UniProtKB ID as representative of the entire gene, including all transcript and protein isoforms.';
