import React from 'react';
import PropTypes from 'prop-types';

import { AttributeList, AttributeLabel, AttributeValue } from '../../components/attribute';
import CrossReferenceListCuration from '../../components/CrossReferenceListCuration.jsx';
import DataSourceLinkCuration from '../../components/dataSourceLinkCuration.jsx';
import SynonymListCuration from '../../components/SynonymListCuration.jsx';
import ModGeneDescription from './modGeneDescription.jsx';
import HelpPopup from '../../components/helpPopup.jsx';
import { getSpecies, getSpeciesNameCorrected, getNoteText } from '../../lib/utils';
import GeneSymbolCuration from '../../components/GeneSymbolCuration.jsx';
import SpeciesName from '../../components/SpeciesName.jsx';

const helpAutomatedDescription =
  'This gene description is generated by an algorithm developed by the Alliance that uses highly structured gene data such as associations to various ontology terms (e.g., Gene Ontology terms) and the Alliance strict orthology set. The original set of ontology terms that a gene is annotated to may have been trimmed to an ancestor term in the ontology, in order to balance readability with the amount of information in the description. The complete set of annotations to this gene may be found in the relevant data tables below.';

const GeneSummary = ({ gene, crossReferenceMap }) => {
  const speciesName = getSpeciesNameCorrected(gene.taxon?.name);
  const synopsisProvider = getSpecies(gene.taxon?.curie)?.geneSynopsisProvider || gene.dataProvider?.abbreviation;

  const automatedDescription = getNoteText(gene.relatedNotes, 'automated_gene_description');
  const modDescription = getNoteText(gene.relatedNotes, 'MOD_provided_gene_description');

  // Combine geneSynonyms and geneSystematicName
  const synonyms = [
    ...(gene.geneSynonyms || []),
    ...(gene.geneSystematicName ? [gene.geneSystematicName] : []),
  ];

  const otherCrossRefs = crossReferenceMap?.other || [];

  return (
    <AttributeList>
      <AttributeLabel>Species</AttributeLabel>
      <AttributeValue>
        <SpeciesName>{speciesName}</SpeciesName>
      </AttributeValue>

      <AttributeLabel>Symbol</AttributeLabel>
      <AttributeValue>
        <GeneSymbolCuration gene={gene} />
      </AttributeValue>

      <AttributeLabel>Name</AttributeLabel>
      <AttributeValue>{gene.geneFullName?.displayText}</AttributeValue>

      <AttributeLabel>Synonyms</AttributeLabel>
      <AttributeValue placeholder="None">
        {synonyms && synonyms.length > 0 && <SynonymListCuration synonyms={synonyms} />}
      </AttributeValue>

      <AttributeLabel>Biotype</AttributeLabel>
      <AttributeValue>{gene.geneType?.name?.replace(/_/g, ' ')}</AttributeValue>

      <AttributeLabel>
        Automated Description{' '}
        {helpAutomatedDescription && <HelpPopup id={'help-gene-auto-desc'}>{helpAutomatedDescription}</HelpPopup>}
      </AttributeLabel>
      <AttributeValue>{automatedDescription}</AttributeValue>

      <AttributeLabel>{synopsisProvider} Description</AttributeLabel>
      <AttributeValue>
        {modDescription && (
          <ModGeneDescription description={modDescription} />
        )}
      </AttributeValue>

      <AttributeLabel>Cross References</AttributeLabel>
      <AttributeValue>
        {otherCrossRefs.length > 0 && (
          <CrossReferenceListCuration crossReferences={otherCrossRefs} />
        )}
      </AttributeValue>

      <AttributeLabel>Additional Information</AttributeLabel>
      <AttributeValue>
        {crossReferenceMap?.references && (
          <DataSourceLinkCuration reference={crossReferenceMap.references}>Literature</DataSourceLinkCuration>
        )}
      </AttributeValue>
    </AttributeList>
  );
};

GeneSummary.propTypes = {
  gene: PropTypes.object,
  crossReferenceMap: PropTypes.object,
};

export default GeneSummary;
