name: Automatic mergebacks from main to stage & develop/ui-wg
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  open-mergeback-PR-to-stage:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    env:
      mergeback-prbranchname: ${{ github.event.pull_request.head.ref }}
      mergeback-headbranchname: 'mergeback/main-to-stage/${{ github.event.pull_request.head.ref }}'
      mergeback-basebranchname: 'stage'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: fetch branches
        run: |
          git fetch
      - name: create mergeback branch
        run: |
          git checkout -b ${{ env.mergeback-headbranchname }} origin/${{ env.mergeback-prbranchname }}
      - name: fetch base branch
        run: |
          git fetch origin ${{ env.mergeback-basebranchname }}:${{ env.mergeback-basebranchname }}
      - name: merge in base branch changes
        id: merge-base
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git merge --no-edit ${{ env.mergeback-basebranchname }}
      - name: Abort merge if merging in base branch failed
        if: ${{ steps.merge-base.outcome == 'failure' }}
        run: |
          git merge --abort
      - name: push mergeback branch to github
        run: |
          git push origin ${{ env.mergeback-headbranchname }}
      - name: open PR
        id: pr-create
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          PR_URL=$(gh pr create -B ${{ env.mergeback-basebranchname }} -H ${{ env.mergeback-headbranchname }} \
            -t 'Mergeback of branch ${{ env.mergeback-prbranchname }} to ${{ env.mergeback-basebranchname }}' \
            -b 'Autogenerated through GH-actions.' -a '${{ github.event.pull_request.user.login }}')
          echo "gh-pr-url=$PR_URL" >> $GITHUB_OUTPUT
      - name: approve PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve ${{ steps.pr-create.outputs.gh-pr-url }}
      - name: enable auto-merge on PR
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr merge --auto --merge ${{ steps.pr-create.outputs.gh-pr-url }}
      - name: Post notification if automatic merge of base failed
        if: ${{ steps.merge-base.outcome == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          pr-comment: |
            GH action detected a potential merge conflict with the base branch (${{ env.mergeback-basebranchname }}).
            @${{ github.event.pull_request.user.login }} please resolve the merge conflict and merge the base branch manually.
        run: |
          gh pr comment ${{ steps.pr-create.outputs.gh-pr-url }} --body "${{ env.pr-comment }}"

  open-mergeback-PR-to-develop-ui-wg:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    env:
      mergeback-prbranchname: ${{ github.event.pull_request.head.ref }}
      mergeback-headbranchname: 'mergeback/main-to-develop-ui-wg/${{ github.event.pull_request.head.ref }}'
      mergeback-basebranchname: 'develop/ui-wg'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: fetch branches
        run: |
          git fetch
      - name: create mergeback branch
        run: |
          git checkout -b ${{ env.mergeback-headbranchname }} origin/${{ env.mergeback-prbranchname }}
      - name: fetch base branch
        run: |
          git fetch origin ${{ env.mergeback-basebranchname }}:${{ env.mergeback-basebranchname }}
      - name: merge in base branch changes
        id: merge-base
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git merge --no-edit ${{ env.mergeback-basebranchname }}
      - name: Abort merge if merging in base branch failed
        if: ${{ steps.merge-base.outcome == 'failure' }}
        run: |
          git merge --abort
      - name: push mergeback branch to github
        run: |
          git push origin ${{ env.mergeback-headbranchname }}
      - name: open PR
        id: pr-create
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          PR_URL=$(gh pr create -B ${{ env.mergeback-basebranchname }} -H ${{ env.mergeback-headbranchname }} \
            -t 'Mergeback of branch ${{ env.mergeback-prbranchname }} to ${{ env.mergeback-basebranchname }}' \
            -b 'Autogenerated through GH-actions.' -a '${{ github.event.pull_request.user.login }}')
          echo "gh-pr-url=$PR_URL" >> $GITHUB_OUTPUT
      - name: approve PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve ${{ steps.pr-create.outputs.gh-pr-url }}
      - name: enable auto-merge on PR
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr merge --auto --merge ${{ steps.pr-create.outputs.gh-pr-url }}
      - name: Post notification if automatic merge of base failed
        if: ${{ steps.merge-base.outcome == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          pr-comment: |
            GH action detected a potential merge conflict with the base branch (${{ env.mergeback-basebranchname }}).
            @${{ github.event.pull_request.user.login }} please resolve the merge conflict and merge the base branch manually.
        run: |
          gh pr comment ${{ steps.pr-create.outputs.gh-pr-url }} --body "${{ env.pr-comment }}"
