name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    # Only run on pull requests and PR comments (not issue comments)
    if: |
      github.event_name == 'pull_request' || 
      (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    permissions:
      contents: read
      pull-requests: write
      issues: write
      # id-token: write removed - not needed for this workflow
    uses: alliance-genome/.github/.github/workflows/claude-code-review.yml@main
    with:
      model: claude-sonnet-4-20250514
      max_turns: 30
      # Standardized focus on critical bugs and blockers only
      review_focus: "critical bugs and blockers that could cause runtime errors, data corruption, or system failures in the React UI application"
      trigger_phrase: "@claude"
      use_zen_tools: true
      pr_size_threshold: "300"
      skip_threshold: "25"
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}