name: PR validation
on:
  pull_request:
    types: [synchronize, opened, reopened, edited, labeled, unlabeled]
    branches:
      - test
      - main
      - stage

jobs:
  fail-by-label:
    if: contains(github.event.pull_request.labels.*.name, 'do-not-merge')
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Fail in case Pull Request is labeled with do-not-merge
        run: |
          echo "Pull Request labeled as \"don't merge\"!"
          exit 1
  prettier-check:
    if: github.event.action != 'edited' || github.event.changes.base
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Node install
        run: |
          npm install
      - name: Prettier verification
        run: |
          echo "IF this fails, run 'make pretty'"
          npx prettier --check .
  test-install-build:
    if: github.event.action != 'edited' || github.event.changes.base
    runs-on: ubuntu-latest
    steps:
      - name: Report workflow details
        run: |
          echo "Repository ${{ github.repository }}."
          echo "Trigger ref ${{ github.ref }}, base-ref ${{ github.base_ref }}, head_ref ${{ github.head_ref }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Report files updated in PR
        run: |
          git fetch -q origin ${{ github.base_ref }} ${{ github.head_ref }}
          git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Report runtime details
        run: |
          echo "Github runner OS: ${{ runner.os }}"
      - name: Clean install all npm dependencies to ensure no discrepancies between package-lock.json and package.json
        run: npm install
      - name: Make Dist Folder
        run: mkdir dist
      - name: Run UI Tests and Build
        run: |
          npm run build
          npm run test
