name: PR validation
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]
    branches:
      - test
      - main
      - stage

jobs:
  test-install-build:
    if: github.event.action != 'edited' || github.event.changes.base
    runs-on: ubuntu-20.04
    steps:
      - name: Report workflow details
        run: |
          echo "Repository ${{ github.repository }}."
          echo "Trigger ref ${{ github.ref }}, base-ref ${{ github.base_ref }}, head_ref ${{ github.head_ref }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Report files updated in PR
        run: |
          git fetch -q origin ${{ github.base_ref }} ${{ github.head_ref }}
          git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Report runtime details
        run: |
          echo "Github runner OS: ${{ runner.os }}"
      - name: Node Package Manager Install
        run: npm install --legacy-peer-deps
      - name: Make Dist Folder
        run: mkdir dist
      - name: Npm build
        run: npm run build
