# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v1.0.8
        env:
          webhook_url: ${{ secrets.MOD_LANDING_PAGES_CI_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.MOD_LANDING_PAGES_CI_WEBHOOK_SECRETS }}
