name: mod landing page tests
on:
  pull_request:
    branches:
      - blue_team_code
  push:
    branches:
      - blue_team_code

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=5 origin ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        name: setup node
        with:
          node-version: 12
      - run: npm install
      - run: npm run test

