name: mod landing page tests
on:
  pull_request:
    branches:
      - blue_team_code
  push:
    branches:
      - gh_action-mod-pages-tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=5 origin ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        name: setup node
        with:
          node-version: 12
      - run: npm install
      - uses: mansagroup/nrwl-nx-action@v2
        name: nx
        with:
          targets: test

